LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := \
        main.c \

LOCAL_MODULE := test
LOCAL_MODULE_TAGS := debug
#LOCAL_CFLAGS += -std=gnu99

#LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLE)

LOCAL_MULTILIB := both
LOCAL_MODULE_STEM_32 := $(LOCAL_MODULE)32
LOCAL_MODULE_STEM_64 := $(LOCAL_MODULE)64


include $(BUILD_EXECUTABLE)
